### ISSUE TITLE
Is this a copy of github.com/public-apis/public-apis?

### ISSUE THREAD

**Issue by asim** [public-api-lists/public-api-lists#20]
How does this differ to the public API repo? It looks like a direct copy removing attribution to the original authors.

https://github.com/public-apis/public-apis

**Comment by oxr463** [comment]
This repository has only 32 commits, 1.1k stars, and is only 2 years old from what I can see. The other repository has 2,980 commits, 139k stars, and is at least 4 years old.

**Comment by oxr463** [comment]
Not to mention the use of bit.ly to shorten the GitHub URL, https://public-api-lists.github.io/public-api-lists

Seems like they might be trying to collect analytics.

**Comment by MichaelJapiesBryant** [comment]
Seems you're right. I caught a few dead links here that have been updated on the original as well.

**Comment by soumendrak** [comment]
Check this out: https://github.com/public-apis/public-apis/issues/3104

**Comment by schnappi21** [comment]
@k4sud0n this issue can be closed.

**Comment by k4sud0n** [comment]
I checked the issue late. I'm sorry.
The purpose that I made this repo is for my own use, and I was not used to using git, so I copied the existing contents and made this new repo.
Originally, I was just going to erase the repository, but I don't know what to do because I saw many people still leaving issues or sending PRs.

And for the bit.ly link, I am trying to collect analytics. I just thought that the original github link is so long so I just decided to use url shortener.
