### ISSUE TITLE
question

### ISSUE THREAD

**Issue by aliefe04** [public-api-lists/public-api-lists#61]
what differences this repo has from public-apis

**Comment by median-man** [comment]
> what differences this repo has from public-apis

@aliefe04 see this issue from the public-apis repo. Otherwise, I would like to hear from the maintainers of this repo on your question as its a good one. I believe the time has come for the contributors and users of the hold repo to migrate and this may be a good option due to its large following. So it would be nice if one of the maintainers of this repo could answer your question. Also, I'm curious as to why the original commit history was squashed.

**Comment by schnappi21** [comment]
@aliefe04 @median-man you should check out this [issue](https://github.com/public-apis/public-apis/issues/3104) from the "original" public-apis repository for more information on why people are creating their own API lists.
